version: 3

includes:
  shared:
    taskfile: hack/common/Taskfile_controller.yaml
    flatten: true
    excludes: [] # put task names in here which are overwritten in this file
    vars:
      NESTED_MODULES: api
      API_DIRS: '{{.ROOT_DIR}}/api/...'
      MANIFEST_OUT: '{{.ROOT_DIR}}/api/crds/manifests'
      CODE_DIRS: '{{.ROOT_DIR}}/cmd/... {{.ROOT_DIR}}/internal/... {{.ROOT_DIR}}/api/...'
      COMPONENTS: platform-service-dns
      REPO_URL: 'https://github.com/openmcp-project/platform-service-dns'
      GENERATE_DOCS_INDEX: "true"
      CHART_COMPONENTS: "[]"
      CRDS_COMPONENTS: platform-service-dns
      CRDS_PATH: '{{.ROOT_DIR}}/api/crds/manifests'

tasks:
  platformservice:
    desc: "  Generates a PlatformService manifest for the current version. Set the VERBOSITY env var to overwrite the default verbosity level (INFO)."
    requires:
      vars:
      - VERSION
    vars:
      VERBOSITY:
        sh: echo "${VERBOSITY:-INFO}"
    cmds:
    - cmd: |
        cat << EOF
        apiVersion: openmcp.cloud/v1alpha1
        kind: PlatformService
        metadata:
          name: dns
        spec:
          image: ghcr.io/openmcp-project/images/platform-service-dns:{{.VERSION}}
          verbosity: {{.VERBOSITY}}
        EOF
      silent: true
